"""create campaigns and proposals tables

Revision ID: f44158ce28c2
Revises: 
Create Date: 2026-04-01 19:05:22.173236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f44158ce28c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_prompt', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('selected_proposal_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='campaign_schema'
    )
    op.create_index(op.f('ix_campaign_schema_campaigns_user_id'), 'campaigns', ['user_id'], unique=False, schema='campaign_schema')
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('copy_text', sa.String(), nullable=False),
    sa.Column('script', sa.String(), nullable=False),
    sa.Column('image_prompt', sa.String(), nullable=False),
    sa.Column('target_audience', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('cta_type', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_schema.campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='campaign_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals', schema='campaign_schema')
    op.drop_index(op.f('ix_campaign_schema_campaigns_user_id'), table_name='campaigns', schema='campaign_schema')
    op.drop_table('campaigns', schema='campaign_schema')
    # ### end Alembic commands ###
