"""create_genetic_schema_tables

Revision ID: 6d62af5f1dde
Revises: 
Create Date: 2026-04-07 21:27:52.967436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d62af5f1dde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genetic_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('min_impressions_to_evaluate', sa.Integer(), nullable=False),
    sa.Column('min_days_active', sa.Integer(), nullable=False),
    sa.Column('min_spend_cpa_multiplier', sa.Float(), nullable=False),
    sa.Column('target_cpa_cents', sa.Integer(), nullable=False),
    sa.Column('fitness_weights', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('early_stage_weights', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('emergency_kill_cpa_multiplier', sa.Float(), nullable=False),
    sa.Column('kill_percentile_bottom', sa.Float(), nullable=False),
    sa.Column('ctr_absolute_floor', sa.Float(), nullable=False),
    sa.Column('max_frequency_prospecting', sa.Float(), nullable=False),
    sa.Column('graduated_cpa_threshold', sa.Float(), nullable=False),
    sa.Column('duplicate_min_days_stable', sa.Integer(), nullable=False),
    sa.Column('duplicate_min_weekly_conversions', sa.Integer(), nullable=False),
    sa.Column('duplicate_max_cpa_ratio', sa.Float(), nullable=False),
    sa.Column('duplicate_min_roas', sa.Float(), nullable=False),
    sa.Column('max_budget_increase_pct', sa.Float(), nullable=False),
    sa.Column('budget_increase_interval_days', sa.Integer(), nullable=False),
    sa.Column('duplicates_per_winner', sa.Integer(), nullable=False),
    sa.Column('mutation_rate', sa.Float(), nullable=False),
    sa.Column('crossover_rate', sa.Float(), nullable=False),
    sa.Column('elitism_count', sa.Integer(), nullable=False),
    sa.Column('max_active_campaigns', sa.Integer(), nullable=False),
    sa.Column('mutation_priorities', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='genetic_schema'
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('campaigns_evaluated', sa.Integer(), nullable=False),
    sa.Column('campaigns_duplicated', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('campaigns_killed', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('fitness_scores', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ran_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='genetic_schema'
    )
    op.create_index(op.f('ix_genetic_schema_optimization_runs_user_id'), 'optimization_runs', ['user_id'], unique=False, schema='genetic_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genetic_schema_optimization_runs_user_id'), table_name='optimization_runs', schema='genetic_schema')
    op.drop_table('optimization_runs', schema='genetic_schema')
    op.drop_table('genetic_configs', schema='genetic_schema')
    # ### end Alembic commands ###
